### ISSUE TITLE
EEQA的问题

### ISSUE THREAD

**Issue by myhcjwds** [linmou/CUP#1]
start_token = start_token[0]
IndexError: list index out of range

请问您在复现2020年EMNLP会议论文模型EEQA时，这个问题怎么解决的呀，刚刚看到了您在 原作者下面 的问题提问，所以前来冒昧打扰！ 期待您的恢复！

**Comment by linmou** [comment]
Sorry for the delayed response. Since this issue is irrelevant to this repo, you can send me an email for further solutions. My email addr can be seen in the paper.
